#!/bin/sh
thishome=`pwd`
extention='.h'
cd cass_remi/classes/event/peak
rootcint -f peak_dict.cxx -c peak$extention LinkDef.h
cd $thishome
cd cass_remi/classes/event/channel
rootcint -f channel_dict.cxx -c -I../peak channel$extention LinkDef.h
cd $thishome
cd cass_remi/classes/event/detector
rootcint -f detector_dict.cxx -c -I../peak -I../channel detector$extention LinkDef.h
cd $thishome
cd cass_remi/classes/event
rootcint -f remi_event_dict.cxx -c -Ipeak -Ichannel -Idetector remi_event$extention LinkDef.h
cd $thishome
cd cass_vmi/classes/event
rootcint -f vmi_event_dict.cxx -c vmi_event$extention LinkDef.h
cd $thishome
cd cass_machinedata/classes/event
rootcint -f machine_event_dict.cxx -c machine_event$extention LinkDef.h
cd $thishome
cd cass_pnccd/classes/event
rootcint -f pnccd_event_dict.cxx -c -I../../../LCLS pnccd_event$extention LinkDef.h
cd $thishome
cd cass
rootcint -f cass_event_dict.cxx -c cass_event$extention LinkDef.h


cd $thishome
cd cass_dictionaries
ln -s ../cass_remi/classes/event/peak/peak_dict.cxx .
ln -s ../cass_remi/classes/event/peak/peak_dict.h .
ln -s ../cass_remi/classes/event/channel/channel_dict.cxx
ln -s ../cass_remi/classes/event/channel/channel_dict.h
ln -s ../cass_remi/classes/event/detector/detector_dict.cxx
ln -s ../cass_remi/classes/event/detector/detector_dict.h
ln -s ../cass_remi/classes/event/remi_event_dict.cxx
ln -s ../cass_remi/classes/event/remi_event_dict.h
ln -s ../cass_vmi/classes/event/vmi_event_dict.cxx
ln -s ../cass_vmi/classes/event/vmi_event_dict.h
ln -s ../cass_machinedata/classes/event/machine_event_dict.cxx
ln -s ../cass_machinedata/classes/event/machine_event_dict.h
ln -s ../cass_pnccd/classes/event/pnccd_event_dict.cxx
ln -s ../cass_pnccd/classes/event/pnccd_event_dict.h
ln -s ../cass/cass_event_dict.cxx
ln -s ../cass/cass_event_dict.h
ln -s ../cass_machinedata/classes/event/machine_event.cpp
ln -s ../cass_remi/classes/event/peak/peak.cpp
ln -s ../cass_remi/classes/event/channel/channel.cpp
ln -s ../cass_remi/classes/event/detector/detector.cpp
ln -s ../cass_remi/classes/event/remi_event.cpp
ln -s ../cass_vmi/classes/event/vmi_event.cpp
ln -s ../cass_pnccd/classes/event/pnccd_event.cpp
ln -s ../cass_remi/classes/event/remi_event.h
ln -s ../cass_remi/remi_analysis.h
ln -s ../cass_remi/cass_remi.h
ln -s ../cass_remi/classes/signalanalyzer/signal_analyzer.h
ln -s ../cass_remi/classes/signalanalyzer/softtdc.h
ln -s ../cass_remi/classes/detektorhitsorter/detektorhitsorter.h
