#ifndef CASS_IMAGEPROCESSOR_GLOBAL_H
#define CASS_IMAGEPROCESSOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CASS_IMAGEPROCESSOR_LIBRARY)
#  define CASS_IMAGEPROCESSORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CASS_IMAGEPROCESSORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CASS_IMAGEPROCESSOR_GLOBAL_H
