#ifndef CASS_DATABASE_GLOBAL_H
#define CASS_DATABASE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CASS_DATABASE_LIBRARY)
#  define CASS_DATABASESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CASS_DATABASESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CASS_DATABASE_GLOBAL_H
