#!/bin/bash

OUTFILE=jocassview_version.h
INCLUDEGUARD=_JOCASSVIEW_VERSION

unset GIT_DIR
unset GIT_WORK_TREE
VERSION=$(git describe --abbrev=4)

if [ -f ${OUTFILE} ] && [ $(cat ${OUTFILE} | grep ${VERSION} | wc -l) -eq 1 ]; then
  echo "${OUTFILE} does contain the latest information."
else
  echo "Generating file for VERSION: v${VERSION}"
  echo " /* this file is auto generated by the update-version.sh script */

/**
 * @file jocassview_version.h auto generated file containing the cass version derived
 *                            from git tags and commit id
 */

#ifndef ${INCLUDEGUARD}
#define ${INCLUDEGUARD}

#include <string>

#define ${INCLUDEGUARD}

namespace jocassview
{
  const std::string VERSION(\"v${VERSION}\");
}

#endif" > ${OUTFILE}
fi
